title: EDM Portfolio
logo: ![Image](https://github.com/user-attachments/assets/d234e305-6b05-4060-9bb0-52ed58da0429)
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
